# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  game_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    command: erl -pa _build/default/lib/*/ebin -eval "application:start(web)" -noshell +Bd